services:
  - type: web
    name: twitch-chatgpt-bot
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        value: "AIzaSyDNC337xHdNgBcHAE8GtdaIUDErEOXx1HU"
      - key: CHANNELS
        value: "deathwish_xoxo"
      - key: GPT_MODE
        value: "CHAT"
      - key: HISTORY_LENGTH
        value: "3"
      - key: MODEL_NAME
        value: "gemini-1.5-flash"
      - key: COMMAND_NAME
        value: "chat"
      - key: TWITCH_USER  # https://dev.twitch.tv/console
        value: "oSetinhasBot"
      - key: TWITCH_AUTH  # https://twitchapps.com/tmi/
        value: "oauth:9wh6ujbu2mro28zhbl8z6z921iuyxz"
      - key: SEND_USERNAME
        value: "true"
      - key: ENABLE_TTS
        value: "false"
      - key: ENABLE_CHANNEL_POINTS
        value: "false"
